### ISSUE TITLE
More info for devices scan can be nice

### ISSUE THREAD

**Issue by guyluz11** [osociety/vernet#6]
It will be nice if the app can show more info on the devices that got found.

- [x] mDNS name - blocker https://github.com/git-elliot/network_tools/issues/6
- [x] Host-name - blocker https://github.com/git-elliot/network_tools/issues/3
- [x] IP
- [x] Mac Address - blocker https://github.com/git-elliot/network_tools/issues/7
- [x] Vendor - blocker https://github.com/git-elliot/network_tools/issues/8
- [x] Response time - blocker https://github.com/git-elliot/network_tools/issues/9

**Comment by guyluz11** [comment]
As getting Mac address #7 has some kind of blocker we can resolve this by adding native dependencies depending on the platform.

I am sure there is one for Android and IOS.

**Comment by guyluz11** [comment]
I think for mDNS our best option for now is to implement android/ios only package and do it here and not part of [network_tools](https://pub.dev/packages/network_tools).

Our options are [nsd](https://pub.dev/packages/nsd), [flutter_mdns_plugin](https://pub.dev/packages/flutter_mdns_plugin), [mdns_plugin](https://pub.dev/packages/mdns_plugin).

For Flutter Linux we can try executing bash commands like `avahi-browse --all` or `mdns-scan` that both of them do not come by default with Linux and are required to get installed separately.

**Comment by guyluz11** [comment]
[nsd](https://pub.dev/packages/nsd) retrieve mDNS name and Host name and it looks like it is well maintained.
It seems that the scan is going to retrieve the IP as well which will make it much easer for us to combine the info bout the device with our IP list.
So let's wait for this feature to get implemented, it will save us a lot of work 
https://github.com/sebastianhaberey/nsd/issues/7

**Comment by guyluz11** [comment]
The feature got implemented, will remove the blocker now

**Comment by guyluz11** [comment]
I am having trouble getting Host-name of devices.
I think it is dart bug and not our code
[Opened issue](https://github.com/dart-lang/sdk/issues/49608) for that in dart-lang SDK repo.

The code supposes to work when the bug is fixed without changing anything.

**Comment by guyluz11** [comment]
The issue moved from dart-lang SDK repo to [flutter repo](https://github.com/flutter/flutter/issues/109220#issuecomment-1210255309) as it is only on flutter android.
